version: '3.9'

services:
  web:
    image: 'jekyll/jekyll:3.8'
    volumes:
      - '.:/app'
    working_dir: '/app'
    ports:
      - '10529:4000'
      - '35729:35729'
    command: 'jekyll serve --livereload'